import { AppDataSource } from '../db/data-source.ts';
//now uuid autogenerated
const createTableQuery = `
  CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

  CREATE TABLE IF NOT EXISTS users (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    name TEXT NOT NULL,
    surname TEXT NOT NULL,
    email TEXT UNIQUE NOT NULL,
    meta JSONB
  );
`;
let initialized = false;

(async () => {
    try {
      await AppDataSource.initialize();
      initialized = true;
      const queryRunner = AppDataSource.createQueryRunner();
      await queryRunner.connect();
      queryRunner.query(createTableQuery);

      console.log("Table created");
    } catch(err: any) {
      console.error("Table not created: ", err);
    } finally {
      if (initialized) {
        await AppDataSource.destroy();
      }
    }
})();